In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib as mpl
%matplotlib inline
mpl.style.use('ggplot')

In [2]:
me=pd.read_csv('finaldataset.csv')

In [3]:
X=me[['City','Area','Location','bhk']]
y=me['Price']

In [4]:
X

City    Area                         Location  bhk
0      Bangalore  3340.0                 JP Nagar Phase 1  4.0
1      Bangalore  1045.0       Dasarahalli on Tumkur Road  2.0
2      Bangalore  1179.0  Kannur on Thanisandra Main Road  2.0
3      Bangalore  1675.0                     Doddanekundi  3.0
4      Bangalore  1670.0                          Kengeri  3.0
...          ...     ...                              ...  ...
18736  Hydarabad  1460.0                         Nacharam  2.0
18737  Hydarabad  1314.0                        Manikonda  2.0
18738  Hydarabad  2625.0                         Madhapur  3.0
18739  Hydarabad  2050.0                      Hitech City  3.0
18740  Hydarabad  1805.0                         Narsingi  3.0

[18741 rows x 4 columns]

In [5]:
y

0        30000000.0
1         7888000.0
2         4866000.0
3         8358000.0
4         6845000.0
            ...    
18736    11000000.0
18737    26000000.0
18738    13300000.0
18739    10800000.0
18740    10400000.0
Name: Price, Length: 18741, dtype: float64

In [6]:
from sklearn.model_selection import train_test_split
import pickle
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import make_column_transformer
from sklearn.pipeline import make_pipeline
from sklearn.metrics import r2_score
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.9)

In [11]:
from sklearn.linear_model import LinearRegression

In [12]:
ohe=OneHotEncoder()
ohe.fit(X[['City','Area','Location','bhk']])

OneHotEncoder()

In [13]:
column_trans=make_column_transformer((OneHotEncoder(categories=ohe.categories_),['City','Area','Location','bhk']),
                                    remainder='passthrough')

In [14]:


lr=LinearRegression()



In [15]:
pipe=make_pipeline(column_trans,lr)

In [16]:
pipe

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(categories=[array(['Bangalore', 'Chennai', 'Dehli', 'Hydarabad', nan], dtype=object),
                                                                            array([  200.,   210.,   220., ..., 12552., 16000.,    nan]),
                                                                            array(['1 Lane Johri Farm', '10 Sector Dwarka', '200 Feet Radial Road',
       ..., 'vikaspuri', 'west venkatapuram', nan], dtype=object),
                                                                            array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8., nan])]),
                                                  ['City', 'Area', 'Location',
                                                   'bhk'])])),
                ('linearregression', LinearRegression())])

In [17]:
pipe.fit(X_train,y_train)

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(categories=[array(['Bangalore', 'Chennai', 'Dehli', 'Hydarabad', nan], dtype=object),
                                                                            array([  200.,   210.,   220., ..., 12552., 16000.,    nan]),
                                                                            array(['1 Lane Johri Farm', '10 Sector Dwarka', '200 Feet Radial Road',
       ..., 'vikaspuri', 'west venkatapuram', nan], dtype=object),
                                                                            array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8., nan])]),
                                                  ['City', 'Area', 'Location',
                                                   'bhk'])])),
                ('linearregression', LinearRegression())])

In [18]:
y_pred=pipe.predict(X_test)

In [19]:
y_pred

array([ 4400137.72355512, 19550786.26189488,  2391083.99554631, ...,
        6082942.66230931,  8588701.1799241 , 11751475.58858159])

In [20]:
y_test

12409     5500000.0
13645    12300000.0
15341     2266000.0
5509      2899000.0
1651      6808000.0
            ...    
12194     2800000.0
7641      6300000.0
16785     3960000.0
1777      8800000.0
2894      6183000.0
Name: Price, Length: 16867, dtype: float64

In [21]:
pickle.dump(pipe,open('LinearRegressionModel.pkl','wb'))

In [22]:
pipe.predict(pd.DataFrame([['Bangalore', 1179.0, 'Kannur on Thanisandra Main Road', 2.0 ]], columns=['City','Area','Location','bhk']))

array([11083799.50142123])